name: chatapp
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'


dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.4
  retrofit: ^3.0.1
  json_serializable: ^6.0.0
  get_it: ^7.2.0

  provider: ^6.0.0
  mockito: ^5.0.0
  flutter_local_notifications: ^9.0.0
  image_picker: ^0.8.4
  build_runner: ^2.3.0
  json_annotation: ^4.6.0
  hive: ^2.0.0
  hive_flutter: ^1.1.0
  hive_generator: ^1.1.0
  cloud_firestore: ^4.13.6
  firebase_auth: ^4.4.0
  firebase_storage: ^11.6.0
  firebase_messaging: ^14.2.5
  firebase_auth_mocks: ^0.9.0




  cupertino_icons: ^1.0.2
  firebase_core: ^2.24.2

dev_dependencies:
  flutter_test:
    sdk: flutter




  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true


